dataset:
    name        : "perineural_nets"
    root        : "/home/modro/datino/perineural_nets"
    all_frames  : ['014', '015', '016', '017', '019', '020', '021', '022', '023', '026', '027', '028', '034', '035', '036', '041', '042', '043', '044', '048', '049', '050', '051', '052', '053']
    # Split ttVtt - ttVtt - .... --> used only if specular_split is false
    train_frames: ['014', '015', '017', '019', '020', '021', '023', '026', '027', '028', '035', '036', '041', '042', '044', '048', '049', '050', '052', '053']
    val_frames  : ['016', '022', '034', '043', '051']
    bbox_discard_min_vis: 0.5
    load_in_memory: False
    percentage: null
    train_with_precomputed_patches: true
    specular_split: true
    crop_width: 640
    crop_height: 640
    overlap_val_patches: 0    # in pixel


model:
    device                 : "cuda"    # cpu or cuda
    backbone               : "resnet50"    # resnet50 or resnet101
    backbone_pretrained    : true   # on ImageNet
    coco_model_pretrained  : true   # on COCO; if true, no need to load the pretrained backbone
    cache_folder           : "./model_zoo"
    max_dets_per_image     : 200
    nms                    : 0.3
    det_thresh             : 0.05
    det_thresh_for_counting: 0.3


training:
    batch_size          : 8
    val_batch_size      : 1
    num_workers         : 4
    epochs              : 100
    seed                : 10
    checkpoint          : ""      # checkpoint to resume, useful for starting from an interrupted training
    pretrained_model    : ""      # pre-trained model to resume
    tensorboard_filename: "faster_rcnn_resnet50_coco_PerineuralNets_640-640-specular_nms-07_detThresh4Counting-03_valPatchesOverlap-0_bs8"
    lr                  : 0.005
    momentum            : 0.9
    weight_decay        : 0.0005
    lr_gamma            : 0.1
    lr_step_size        : [25, 50, 100]
    print_freq          : 10
    val_freq            : 1
    log_loss            : 10
    debug               : true
    debug_freq          : 3
    coco_max_dets       : 2000
