dataset:
    name        : "perineural_nets"
    root        : "/mnt/Dati_SSD_2/datasets/perineural_nets"
    all_frames  : ['014', '015', '016', '017', '019', '020', '021', '022', '023', '026', '027', '028', '034', '035', '036', '041', '042', '043', '044', '048', '049', '050', '051', '052', '053']
    # Split ttVtt - ttVtt - .... --> used only if specular_split is false
    train_frames: ['014', '015', '017', '019', '020', '021', '023', '026', '027', '028', '035', '036', '041', '042', '044', '048', '049', '050', '052', '053']
    val_frames  : ['016', '022', '034', '043', '051']
    crop_width: 640
    crop_height: 640
    load_in_memory: False
    percentage: null
    train_with_precomputed_patches: true
    specular_split: true
    overlap_val_patches: 0    # in pixel


model:
    name                 : "CSRNet"   # can be UNet or CSRNet
    device               : "cuda"    # cpu or cuda
    cache_folder         : "./model_zoo"


training:
    batch_size          : 2
    val_batch_size      : 1
    num_workers         : 4
    epochs              : 100
    seed                : 10
    tensorboard_filename: "CSRNet_PerineuralNets_640-640-specular_valPatchesOverlap-0_MSE_bs2"
    lr                  : 0.00001
    lr_step_size        : [50, 75, 100]
    lr_gamma            : 0.1
    momentum            : 0.95
    weights_decay       : 0.0005
    checkpoint          : ""      # checkpoint to resume, useful for starting from an interrupted training
    pretrained_model    : ""      # pre-trained model to resume
    loss                : "MeanSquaredError"
    aux_loss            : null    # can be "SSIM" or null
    lambda_aux_loss     : 10
    optimizer           : "Adam"     # can be Adam or SGD
    val_freq            : 1
    debug               : true
    debug_freq          : 3
    log_loss            : 20
