# @package _group_
dataset:
    train:
        name: "perineural_nets"
        params:
            root: ${hydra:runtime.cwd}/data/perineuronal_nets
            split: train-specular
            patch_size: 320     # must be divisible by 32
            overlap: 0
            random_offset: null  # auto-determined as patch_size / 2
            max_cache_mem: 8_589_934_592  # 8GiB in bytes
            gt_params:
                'k_size': 51         # size (in px) of the kernel of the gaussian localizing a perineural nets
                'sigma': 30            # sigma of the gaussian

    validation:
        name: perineural_nets
        params:
            root: ${hydra:runtime.cwd}/data/perineuronal_nets
            split: validation-specular
            patch_size: 320     # must be divisible by 32
            border_pad: 64      # must be divisible by 32
            overlap: null        # auto-determined as 4 * gt_params.radius_ignore
            random_offset: 0
            max_cache_mem: 8_589_934_592  # 8GiB in bytes
            gt_params:
                'k_size': 51         # size (in px) of the kernel of the gaussian localizing a perineural nets
                'sigma': 30            # sigma of the gaussian


model:
    name: UNet        # can be CSRNet or UNet
    cache_folder: ./model_zoo
    pretrained: null     # path to pretrained weights, optimizer states will not restored
    resume: null    # path to last trained model, will restore optimizer states
    params:
        load_weights: False
        in_channels: 3
        n_classes: 1
        padding: True
        batch_norm: True


optimizer:
    name: Adam
    params:
        lr: 0.00001
    scheduler:
        name: MultiStepLR
        params:
            milestones: [50, 75, 100]
            gamma: 0.1
    loss:
        name:
            MSELoss


train:
    batch_size: 8
    val_batch_size: 8
    num_workers: 4
    epochs: 100
    val_freq: 1
    debug: true
    debug_freq: 2
    log_every: 20
    batch_accumulation: 1
    val_device: cpu


seed: 10
gpu : 0      # index of the gpu you want to use, null for cpu




