# @package _group_
dataset:
    train:
        name: "PerineuralNetsDetDataset"
        params:
            root: ${hydra:runtime.cwd}/data/perineuronal_nets
            split: train-specular
            patch_size: 320
            overlap: 0
            random_offset: null  # auto-determined as patch_size / 2
            max_cache_mem: 8_589_934_592  # 8GiB in bytes
            num_sample: null
            gt_params:
                side: 60       # side (in px) of the bounding box localizing a cell
                in_memory: null
                ann_type: null

    validation:
        name: "PerineuralNetsDetDataset"
        params:
            root: ${hydra:runtime.cwd}/data/perineuronal_nets
            split: validation-specular
            patch_size: 320
            overlap: null        # auto-determined as 4 * gt_params.radius_ignore
            random_offset: 0
            max_cache_mem: 8_589_934_592  # 8GiB in bytes
            num_sample: null
            gt_params:
                side: 60       # side (in px) of the bounding box localizing a cell
                in_memory: null
                ann_type: null


model:
    name: "faster_rcnn"
    backbone: "resnet50"    # resnet50 or resnet101
    backbone_pretrained: true   # on ImageNet
    coco_model_pretrained: true   # on COCO; if true, no need to load the pretrained backbone
    cache_folder: ./model_zoo
    pretrained: null     # path to pretrained weights, optimizer states will not restored
    resume: null    # path to last trained model, will restore optimizer states
    params:
        max_dets_per_image: 200
        nms: 0.3
        det_thresh: 0.05


optimizer:
    name: SGD
    params:
        lr: 0.005
        momentum: 0.9
        weight_decay: 0.0005
    scheduler:
        name: MultiStepLR
        params:
            milestones: [75, 100, 125]
            gamma: 0.1


train:
    batch_size: 8
    val_batch_size: 8
    num_workers: 4
    epochs: 125
    val_freq: 1
    log_every: 20
    debug: true
    debug_freq: 2
    batch_accumulation: 1
    val_device: cpu


seed: 10
gpu : null     # index of the gpu you want to use, null for cpu
