# @package _global_

method: countmap

data:
    train:
        transforms:
            _target_: torchvision.transforms.Compose
            _args_: 
                - - _target_: torchvision.transforms.ToTensor
                  - _target_: torchvision.transforms.RandomHorizontalFlip
    validation:
        transforms:
            _target_: torchvision.transforms.ToTensor

optim:
    loss:
        _target_: torch.nn.L1Loss