# @package _global_

model:
    base:
        num_classes: 1
    wrapper:
        _target_: spacecutter.models.OrdinalLogisticModel
        num_classes: 8
        predictor: ${model.base}            

optim:
    method: ordinal_regression
    batch_size: 32
