# @package _global_

model:
    base:
        num_classes: 8

optim:
    method: simple_classification
    batch_size: 32
    optimizer:
        _target_: torch.optim.SGD
        momentum: 0.9
        lr: 0.001
    
    epochs: 200
    lr_scheduler:
        milestones: [60]